Update Android grade plugin
This also adds jcenter because this is where the new plugin versions are
hosted.

This also updates Robolectric, because the plugin update changes build
outputs that Robolectric relies on:

```
java.lang.RuntimeException: java.lang.RuntimeException:
build/intermediates/manifests/full/debug/AndroidManifest.xml not found
or not a file; it should point to your project's AndroidManifest.xml
```