Fix JavaDoc warnings
Previously we'd get a lot of warnings like:

```
  symbol:   class Nullable
  location: class Analytics
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/Analytics.java:604: error: cannot find symbol
      final @NonNull String event,
             ^
  symbol:   class NonNull
  location: class Analytics
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/Analytics.java:605: error: cannot find symbol
      final @Nullable Properties properties,
             ^
  symbol:   class Nullable
  location: class Analytics
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/Analytics.java:606: error: cannot find symbol
      @Nullable final Options options) {
       ^
  symbol:   class Nullable
  location: class Analytics
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/Analytics.java:641: error: cannot find symbol
  public void screen(@Nullable String category, @Nullable String name) {
                      ^
  symbol:   class Nullable
  location: class Analytics
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/Analytics.java:641: error: cannot find symbol
  public void screen(@Nullable String category, @Nullable String name) {
                                                 ^
  symbol:   class Nullable
  location: class Analytics
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/Analytics.java:650: error: cannot find symbol
      @Nullable String category, @Nullable String name, @Nullable Properties properties) {
       ^
  symbol:   class Nullable
  location: class Analytics
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/Analytics.java:650: error: cannot find symbol
      @Nullable String category, @Nullable String name, @Nullable Properties properties) {

```

I fixed these based on  https://github.com/chrisbanes/gradle-mvn-push/issues/39#issue-42709896. This made the output less noisy and surfaced some real bugs in the current javadocs.

```

> Task :analytics:androidJavadocs
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/AnalyticsContext.java:53: error: package com.segment.analytics.core does not exist
import com.segment.analytics.core.BuildConfig;
                                 ^
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/Analytics.java:493: warning - Tag @see: missing final '>': "<a href="https://segment.com/docs/spec/identify/">Identify Documentation</a>."
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/AnalyticsContext.java:557: warning - @Set is an unknown tag.
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/Options.java:87: warning - Tag @see:illegal character: "123" in "{@link Options#setIntegration(String, boolean)}"
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/Options.java:87: warning - Tag @see:illegal character: "64" in "{@link Options#setIntegration(String, boolean)}"
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/Options.java:87: warning - Tag @see: reference not found: {@link Options#setIntegration(String, boolean)}
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/integrations/Integration.java:70: warning - Tag @see:illegal character: "125" in "Analytics#screen(String, String, com.segment.analytics.Properties,
     com.segment.analytics.Options)}"
7 warnings

```

I was able to fix almost all of these. Now only the first one is left:

```

> Task :analytics:androidJavadocs
/Users/prateek/dev/src/github.com/segmentio/analytics-android/analytics/src/main/java/com/segment/analytics/AnalyticsContext.java:53: error: package com.segment.analytics.core does not exist
import com.segment.analytics.core.BuildConfig;
                                 ^
1 warning

```

It's unclear how to fix this one given for the momement that the BuildConfig file is generated during the build process.